t = 2:0.01:2.2;
w1 = 30;
iData = 100*sin(1.3*w1.*t+pi/4)+50*exp(-t/0.1);
%用最小二乘求解非线性曲线拟合（数据拟合）问题（lsqcurvefit函数）
fun = @(fit,t)fit(1)...
    -fit(2).*t...
    +sin(1*w1.*t)*fit(3)...
    +sin(2*w1.*t)*fit(4)...
    +sin(3*w1.*t)*fit(5)...
    +sin(4*w1.*t)*fit(6)...
    +sin(5*w1.*t)*fit(7)...
    +cos(1*w1.*t)*fit(8)...
    +cos(2*w1.*t)*fit(9)...
    +cos(3*w1.*t)*fit(10)...
    +cos(4*w1.*t)*fit(11)...
    +cos(5*w1.*t)*fit(12);
x0 = ones(1,12)*max(iData);
fit = lsqcurvefit(fun,x0,t,iData);
fitData = fun(fit,t);
figure;
hold on;
plot(t,iData);
plot(t,fitData);
legend('测量值',"最小二乘法拟合值");
xlabel("时间t/s")
ylabel("电流I/A")
hold off;
p1 = sqrt(fit(3)^2+fit(8)^2);
deg1 = asin(fit(3)/p1);
p2 = sqrt(fit(4)^2+fit(9)^2);
deg2 = asin(fit(4)/p1);
formatSpec = '基波频率%.2f(Hz) 相角(弧度)%.2f 幅值%.2f\n';
fprintf(formatSpec,w1/(2*pi),deg1,p1);
formatSpec = '一次谐波频率%.2f(Hz) 相角(弧度)%.2f 幅值%.2f\n';
fprintf(formatSpec,w1*2/(2*pi),deg2,p2);
